name: simple

on: [push]

jobs:
  simple:
    name: Test `cargo check/test/build`
    runs-on: ubuntu-latest

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v4

      - run: rustup toolchain install stable --profile minimal --no-self-update

      - uses: ./
        with:
          workspaces: tests

      - run: |
          cargo install cargo-sort
        working-directory: tests
